# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lumedeir < lumedeir@student.42sp.org.br    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/24 14:58:11 by lumedeir          #+#    #+#              #
#    Updated: 2023/09/11 11:55:06 by lumedeir         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# The name of the executable
NAME = pipex
# Compilation flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror -g3
# Directories
INCLUDE = -I./src/includes
LIBFT = ./src/Libft
BUILD = ./objs/

# Source files mandatory
SRC =	error.c \
		pipex.c \
		pipex_utils.c

# Building object files
$(BUILD)%.o:src/%.c
		@mkdir -p $(BUILD) 
		@$(CC) $(CFLAGS) -c $< -o $@ $(INCLUDE)

OBJ = $(addprefix $(BUILD), $(SRC:.c=.o))

# Color codes for terminal output
PURPLE = \033[1;35m
CYAN= \033[0;36m

# The default target calling for the executable
all : $(NAME)

# The target to build the mandatory part
$(NAME) : $(OBJ)
	@make -C $(LIBFT) --silent
	@$(CC) $(OBJ) $(CFLAGS) $(LIBFT)/libft.a -o $(NAME)
	@echo "$(CYAN)The Makefile of [$(PURPLE)PIPEX$(CYAN)] has been compiled!🤠"


# Cleans object files and dependencies
clean:
		@make clean -C $(LIBFT) --silent
		@rm -rf $(BUILD)

fclean: clean
		@echo "Cleaning all... 🧹"
		@make fclean -C $(LIBFT) --silent
		@rm -f $(NAME)
		@echo "✨ Cleaning complete! ✨"

# Cleans everything generated by the Makefile and rebuild all
re: fclean all

# Phony targets
.PHONY: all clean fclean re